import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import DarkModeProvider from "@/context/darkMode/DarkModeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <DarkModeProvider>
          {
            <>
              <Navbar />
              {children}
              <Footer />
            </>
          }
        </DarkModeProvider>
      </body>
    </html>
  );
}
